### ISSUE TITLE
Client secret or other secrets shouldn't be committed into the codebase

### ISSUE THREAD

**Issue by ALiangLiang** [xDDoubleTea/Discord-bot#15]
https://github.com/xDDoubleTea/Discord-bot/blob/625f6e990629be378b65ff81d787c233b40bec7b/Kanata.py#L30
https://github.com/xDDoubleTea/Discord-bot/blob/9a1a9b05b9f36cf3d4c6c7c5307b18cca53a48c8/Kanata.py#L731

If you already committed, you can ref [this post](https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history) to remove them from codebase

**Comment by xDDoubleTea** [comment]
Thank you for reminding me to remove it ❤️
